### ISSUE TITLE
Flux de veille

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#1206]
Dans le tableau de veille 
![Capture](https://user-images.githubusercontent.com/37538697/123433072-5a00a080-d5cb-11eb-9bb5-aa707680b429.PNG)
Le dernier paquet de veille est le 2.63.0. Il apparait dans l'admin, que le dernier paquet de modification des conventions collectives est le 2.91.0.

La mise à jour de ce flux permet de mieux traiter les modifications à apporter aux contributions impactées par un changement sur les références juridiques.

Solution: 
Analyser la cause du disfonctionnement de flux de veille, et y remédier durablement.

**Comment by lionelB** [comment]
closed in favor of https://github.com/SocialGouv/cdtn-admin/issues/504
