### ISSUE TITLE
[suite déploiement 75] Ordonnancement du backlog

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#152]
Pour la campagne, la référence au numéro de la question peut être importante pour les usagers ( certaines régions ayant opéréré un partage de liate initale en fonction de ces numéros)
**Dans la page liste de réponses, et pour les les questions à rédiger:**
> Pour être plus lisibles, ces questions numérotées doivent:
* être ordonnée en fonction de leur numéro ( du plus petit au plus grand)
*apparaître en tête de liste, si d'autre question non numérotées figurent dans le backlog

> Ordonnancement actuel des questions en cours/brouillon, qui semble être par ordre chrono parait satisfaisant.

paradise?: possibilité de trier les réponses à rédiger de la liste à faire par :
- chronologie
- A-Z
-1,2,3...

**Comment by ClementChapalain** [comment]
done non ? @jrduscher @ivangabriele

**Comment by ClementChapalain** [comment]
done
