### ISSUE TITLE
[suite déploiement UD75] Renvois au Code du travail, renvoi CCN

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#154]
L'utilisateur, dans le menu édition, déplore de devoir revenir sur la liste des questions, pour procéder au renvoi vers le code du travail.

1) dans la page Edition, au cours de l’édition du brouillon, je dois pouvoir finalement renvoyer au code du travail/ccn sans sortir de la page Edition.

UX needed
retours à confirmer

2) ne pas toucher à implication suivante: une réponse renvoyée au code du travail devient un brouillon, si je l'ouvre Et si j'apporte des modifications

**Comment by ClementChapalain** [comment]
On a eu ce retour qu'une seule fois si je ne me trompe pas et ce n'est pas vraiment pas cohérent avec notre interface (devoir aller sur une page avec plein de fonctionnalités d'édition pour ne finalement ne utiliser aucune n'est pas logique). Je propose qu'on mette en won't fix, mais ça reste ouvert à la discussion si on se rend compte que ça pose vraiment des problèmes.

**Comment by ivangabriele** [comment]
Ça se discute en effet. Mais il y a quelque chose de censé derrière cette remarque: quoiqu'il arrive, même si le contributeur renvoie la réponse, il faut ensuite qu'il l'ouvre pour l'envoyer en validation, ce qui un peu bizarre. Avoir toutes les actions concernant une réponse dans la page d'édition semble plus logique dans ce sens-là non ?

**Comment by jrduscher** [comment]
l'hypothèse de travail qui peut illustrer le besoin serait: en tant que contributeur, je rédige une réponse pour le code du travail numérique, et me rend compte en cours de rédaction que celle ci revêt d'un renvoi à des dispositions du cdtl ou de stipulations conventionnelles.
@ClementChapalain on a un exemple récent d'une admin qui nous saisit d'une réponse avec des dispositions code du travail entièrement rédigées.

**Comment by ClementChapalain** [comment]
ok que pensez-vous de le mettre dans lee menu "autres options" sous le bouton de demande de validation que j'ai proposé dans #78 ?

**Comment by ClementChapalain** [comment]
on pourrait imaginer quelque chose comme ça :
![image](https://user-images.githubusercontent.com/5337489/59269658-e394de00-8c4f-11e9-9b4c-98d3cb2f649b.png)

**Comment by jrduscher** [comment]
Nickel
