### ISSUE TITLE
traiter des conventions collectives locales "métallurgie"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#164]
**La saisie des questions réponses**
Dans la plupart des cas, la convention collective locale couvre un département. Il existe pourtant, des exceptions de deux ordres. il s'agit de cas bien identifiés.
> plusieurs conventions collectives locales sont présentes sur un même département: la granularité est plus fine que le département.
>une ou plusieurs conventions collectives ont un champ d’application qui s'étend à cheval sur plusieurs départements, et pas forcément au sein d'une même région.

1) Les travaux en cours dans cette branche doivent inciter à juste permettre à nos contributeurs de pouvoir saisir leurs questions. 

L'idée pour faire simple: 
question + département. dans le département, on peut avoir plusieurs CCN,une CCN peut être traitée dans plusieurs départements.

a) Page liste de questions: en lieu et place de l'IDCC, on a un département.

Une question+ un département.

le département est identifié par UD de DIRECCTE. UD01, UD02, UD03...;

![image](https://user-images.githubusercontent.com/37538697/57606437-28522a00-7569-11e9-8510-7082c6393068.png)

b) dans les étiquettes, pour ces cas, où l'IDCC peut être multiple: champ libre de saisie

**Comment by ivangabriele** [comment]
A moins que je n'aie pas bien compris, c'est simplement un problème qui se posera du côté des usagers du site et non du côté des contributeurs, non ? Ce que je veux dire, c'est que les contributeurs sont censés parfaitement savoir ce que prévoient les conventions qu'ils couvrent.

**Comment by jrduscher** [comment]
les contributeurs doivent fournir une réponse unique départementale. il existe des CCN au niveau du canton( la ajorité des cas ce son des cc départemeantle). Il vont donc rédiger des réponses pour un département qui parlent de plusieurs cc locales. ils devront pouvoir saisir plusieurs CCN pour une questsion réponsse ou nous devrons le faire pour eux. Donc si si ca se pose carrément côté contrib, mais c'est un cas particulier.

**Comment by adipasquale** [comment]
On vient d'en parler avec Ivan, je mets un peu le holà sur ce ticket. 

Ça me paraît hyper anticipé par rapport à où on en est aujourd’hui ET un très mauvais ROI car très compliqué pour peu de cas particuliers

Que veut-on faire de cette donnée de localisation des CCNs ? Et encore plus de la donnée des cas particuliers ?

**Côté outil de contribution :** 
Ivan me dit qu'il compte l'afficher dans l'outil de contribution, mes questions :

 1. pourquoi doit on l’afficher ? les contributeurs sont censés être des experts de leur CCN pourquoi ont ils besoin de voir cette info ?
2. comment compte-t-on l'afficher ? du texte qui dit “ne s’applique que dans le périgord du Nord et à Dax”, ou bien une map ou bien autre chose ?
3. qu’attend-t-on qu’ils fassent avec cette info affichée ? Sont-ils censés subdiviser leur réponse par sous zone ?

**Côté Frontend :**

pour l’instant le gros point d’entrée prévu pour trouver sa convention c’est de passer par le SIREN auquel cas il n’y a pas du tout besoin de cette info

Si on envisageait de faire trouver à un employé sa convention locale en cherchant par domaine d'activité puis par localisation ça aurait un sens (et encore les cas particuliers ça aurait toujours un coût / impact vraiment pas terrible imho)

L'autre cas serait si on envisage d'aider les employeurs à choisir leur CCN mais je pense que c'est complètement hors-scope non ?

**Comment by jrduscher** [comment]
Une réunion technique a eu lieu sur la question. La solution apportée avec cette issue n'es pas concluante.
