### ISSUE TITLE
Compléter le menu Aide

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#186]
Prévoir l'intégration de deux fichiers d'aide
dont:https://jean-rene-duscher.gitbook.io/code-du-travail-numerique/
et une faq propre à la campagne ( en cours de rédaction)

![image](https://user-images.githubusercontent.com/37538697/57764981-d7773880-7704-11e9-98b9-6dc92cd77929.png)
l'onglet aide doit afficher:
1) le WIKI de l'outil de contribution: "Guide : Outil de contribution"
2) la charte rédactionnelle
3) le WIKI de la campagne de contribution: "Guide : Campagne de contribution"

**Comment by ClementChapalain** [comment]
done pour le wiki, on ouvrira une autre tâche pour la faq propre à la campagne
