### ISSUE TITLE
Design homepage

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#21]
![new mockup 1](https://user-images.githubusercontent.com/5337489/53498731-2f5bb700-3aa7-11e9-96d3-f6f8ddd34164.png)

V1 de la page de login de l'outil de contribution.

Quelques détails :
- le lien en-dessous du bouton `se connecter` renvoie vers `mailto:contact@code-du-travail.beta.gouv.fr`
- la couleur du fond de la partie gauche est #f9f9fc (comme sur la page d'accueil du CDTN)

**Comment by ClementChapalain** [comment]
ping @ivangabriele dis-moi si ça te parait ok :)

**Comment by ivangabriele** [comment]
@ClementChapalain Parfait :+1:

**Comment by ivangabriele** [comment]
#40
