### ISSUE TITLE
BUG: fonction de recherce dans l'adminsitration des recherche

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#214]
![image](https://user-images.githubusercontent.com/37538697/58331631-d8f9dc80-7e39-11e9-9c22-60501a3460ff.png)
partie adminsitration/ Réponses
La saisie ne fonctionne pas et renvoie page blanche et une erreur inattendu. "An unexpected error has occurred."

**Comment by ivangabriele** [comment]
Duplicata de #194 ;)
