### ISSUE TITLE
MVP de la page d'édition

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#24]
MVP : https://invis.io/UQQV5DKS39E
later : https://invis.io/3QQREC6ZGNK

to do MVP :
- [x] ajouter l'indicateur de CCNs
- [ ] permettre l'ajout de références juridiques via un nouvel onglet
- [ ] ajouter un marqueur de sauvegarde automatique
- [x] faire apparaitre la barre d'édition tout le temps
- [x] permettre le retour arrière / retour avant dans l'édition
- [ ] revoir le design du panneau labels
- [x] intégrer le lien vers la charte

to do later :
- [ ] permettre l'ajout d'autres ressources via un nouvel onglet
- [ ] permettre la pré-visualisation via un nouvel onglet
- [ ] permettre l'ajout / modification / suppression de sous-réponses

**Comment by ClementChapalain** [comment]
@jrduscher @ivangabriele j'ai fait une maquette ici pour la page d'édition :
https://invis.io/3QQREC6ZGNK

vous pouvez faire des commentaires directement sur invision si besoin

**Comment by ivangabriele** [comment]
#40
