### ISSUE TITLE
Validation des réponses par un admin V0

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#248]
wip :
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=1015%3A0&viewport=412%2C458%2C0.566326916217804&scaling=min-zoom

**Comment by ClementChapalain** [comment]
@ivangabriele @jrduscher vous en pensez quoi ?

En termes de nouvelle fonctionnalité il faut :
- afficher la réponse (et les sources juridiques et les étiquettes) dans une page
- avoir la possibilité d'ajouter un commentaire sur une réponse
- 2 nouveaux statuts de réponse : refusé et validé
- pouvoir mettre une réponse en refusé ou validé à partir de la page détail d'une réponse
- pouvoir modifier une réponse (et les sources juridiques et les étiquettes) depuis l'admin

Le dernier point me paraît plus compliqué, à la fois en terme de design et techniquement, je n'ai pas vraiment la solution encore. On peut déjà commencer avec le reste je pense.

**Comment by jrduscher** [comment]
super complet sur la partie affichage/modif. 
A imaginer: la communication au contributeur ( réponse+commentaire?)
                   les stats (% todo/% wip/ %done)
                   les possibilités de navigation (filtres) pour l'admin ( filtres par date/période, filtre par IDCC, par UD...)  .
Qu'en pensez vous?

**Comment by ClementChapalain** [comment]
> la communication au contributeur ( réponse+commentaire?)
> les stats (% todo/% wip/ %done)
> les possibilités de navigation (filtres) pour l'admin ( filtres par date/période, filtre par IDCC, par UD...).

oui je suis d'accord ce sont des bons points, il faudra qu'on fasse des tâches distinctes et qu'on voit avec Nadia ce dont elle a besoin une fois qu'elle sera arrivée et qu'elle aura commencé à valider.

**Comment by ClementChapalain** [comment]
update suite à la réunion de cette après-midi :
