### ISSUE TITLE
🚀 Déployer le projet sur une url *.social.gouv.fr

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#25]
backoffice.codedutravail.num.social.gouv.fr ?
contribution.[...] ?
content.[...] ?
admin.[...] ?

vous préférez quoi comme adresse @jrduscher @ivangabriele ?

**Comment by jrduscher** [comment]
contribution.... : si c'est l'url est visible par les agents s; content ou admin si c'est que pour l'équipe projet, les administrateurs

**Comment by ivangabriele** [comment]
- Dev: https://contributions.codedutravail-dev.num.social.gouv.fr

_Prod en attente..._

**Comment by ClementChapalain** [comment]
est-ce que tu peux nous donner l'email qui permet d'accéder à la plateforme stp @ivangabriele ?
