### ISSUE TITLE
Plus de possibilités pour le renvoi au code du travail

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#293]
Lorsqu'un contributeur veut faire un renvoi au code du travail, il doit pouvoir sélectionner parmi les 3 possibilités suivantes : 
- La convention collective renvoie explicitement au code du travail
- La convention collective ne prévoit rien sur ce point
- La convention prévoit une disposition qui ne peut pas s'appliquer

☝️ valider avec Nadia la formulation exacte des 3 possibilités

Niveau design, cette possibilité est enlevée de la page liste des réponses pour simplifier l'interface :
![image](https://user-images.githubusercontent.com/5337489/61778750-a2bbe780-adff-11e9-8135-15bfb802ac49.png)

Et on ajoute un bloc pour sélectionner le renvoi depuis la page d'édition :
![image](https://user-images.githubusercontent.com/5337489/61778801-bb2c0200-adff-11e9-9faf-97912aff0433.png)
![image](https://user-images.githubusercontent.com/5337489/61778821-c54e0080-adff-11e9-98d5-25d22700015c.png)

Prototype cliquable :
https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=60%3A232&viewport=-941%2C65%2C0.6413623094558716&scaling=min-zoom

Partie admin : #310

**Comment by ClementChapalain** [comment]
ping @June-law et @ivangabriele j'ai mis à jour les designs dans la description de la tâche, est-ce que c'est ok pour vous ? la partie admin est toujours dans #310 et ne change pas par rapport à la première version que j'avais fait

**Comment by ivangabriele** [comment]
@ClementChapalain On peut fermer ça du coup ?

**Comment by ClementChapalain** [comment]
oui :)
