### ISSUE TITLE
Créer un profil type "Administrateur régional"

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#331]
**Contexte** : outiller le pilotage régional des contribution par les administrateurs.
**rappel**: L’administrateur régional a en charge le suivi des contributions, le pilotage et la définition de l’organisation régionale de la contribution. Il doit avoir un visuel sur les contributions dans leur ensemble au niveau de la région.

**Créer un profil administrateur régional.**

créer un rôle supplémentaire : Administrateur régional 
_la création de l’utilisateur avec ce nouveau profil ne nécessite pas de nouveau champ.
Le renseignement de l'unité et des CCN associés devraient être utilise pour les fonctionnalités décrites ci après:_

**Description des fonctionnalités et restrictions attendues:**
Mêmes fonctionnalités que le profil administrateur mais circonscrit à la région de l’administrateur:
- accès lecture  Dashboard: uniquement pour la région
- visuel sur les utilisateurs de la région ( = utilisateurs filtrés selon les CCn de la région).
- accès en lecture des questions.
- accès en lecture et modification étiquettes.
- accès aux listes des réponses traitées dans la région ( =filtres par CCN de la région)
- accès en lecture et écriture aux réponses traitées dans la région, sauf statuts de réponse de Nadia 
- possibilité pour l'admin de remettre en brouillon ou réinitialiser une question
- accès en lecture  et modification : "Unité" limité à la région de l’administrateur régional
-accès zones? lecture.

Création du profil administrateur:
créer un profil administrateur régional

**Améliorer le tableau de bord:** (paradise)

ajouter des synthèses:
nombre total des questions à rédiger pour la région
nombre total des questions en cours de rédaction
nombre total des questions en cous de validation
nombre total des questions validées

avancement:
nombre de réponses en cours/faites  
nombre de réponses attendus ( 53 * nombre de CC dela région)
% d'avancement.
( Paradise: une barre de progression)

**Comment by ClementChapalain** [comment]
V1 : juste accès au dashboard de sa région

**Comment by ClementChapalain** [comment]
j'en profite pour vous proposer une maquette pour le dashboard : https://www.figma.com/proto/UGkd7UFF3gJSb3a35ClTtPKW/Code-du-travail-num%C3%A9rique?node-id=1325%3A4097&viewport=1555%2C769%2C0.4040162265300751&scaling=min-zoom

**Comment by ClementChapalain** [comment]
👏 👏
