### ISSUE TITLE
BUG: : trouver un article du code du travail

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#347]
plusieurs doublons sont proposés

![image](https://user-images.githubusercontent.com/37538697/61277157-dec4cc00-a7b1-11e9-8ed9-9ae2c722e8e1.png)

**Comment by revolunet** [comment]
J'ai vérifié dans le dernier fichier issue de l'API DILA (qui est maintenant une liste plate des articles) et il n'apparait qu'une fois : https://github.com/SocialGouv/code-du-travail-numerique/blob/85c268d4af895d1c27c9bce61aeda543446304a0/packages/code-du-travail-data/dataset/code_du_travail/code-du-travail.json

(ce sera mergé sous peu)

@ivangabriele avais-tu une utilisé de la structure du code sous forme de "tree" ?

**Comment by ivangabriele** [comment]
@revolunet Oui mais de toute manière je l'applatis: https://github.com/SocialGouv/code-du-travail-backoffice/blob/dev/scripts/data/extractLawRefs.js#L37
