### ISSUE TITLE
Bug: affichage de la réponse en attente de validation

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#484]
le texte déborde du champ

![image](https://user-images.githubusercontent.com/37538697/64261342-a7120f00-cf2c-11e9-878f-1ce8fc5b3032.png)

**Comment by ClementChapalain** [comment]
on peut avoir un lien ou la question + ccn stp @jrduscher ?

**Comment by jrduscher** [comment]
J'ai reafais un essai ici: dès que la réponse est trop longue elle sort du cadre de texte: 
https://contributions.codedutravail.num.social.gouv.fr/answers/view/e9b82275-3b24-41b2-bfe5-08ef4a6ca1ea
