### ISSUE TITLE
Un contributeur peut ajouter des références juridiques

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#49]
1. permettre à un contributeur d'ajouter des références juridiques :
- articles du code du travail
- liens externes

2. faire en sorte que les références juridiques soient dans un système d'onglet et non dans la barre de l'édition

**Comment by ivangabriele** [comment]
@ClementChapalain C'est done ça non?

**Comment by ClementChapalain** [comment]
yes 2 retours :
- possible d'avoir un auto-complete pour les articles du CDT ? en se basant sur LEGI poke @revolunet 
- il faudrait ajouter un bouton de validation pour chacun des deux champs je pense, le fait de devoir taper "entrée" n'est pas forcément hyper clair

**Comment by revolunet** [comment]
tu peux te base sur https://github.com/SocialGouv/code-du-travail-numerique/blob/master/packages/code-du-travail-data/dataset/code_du_travail/code-du-travail.json si besoin, on mettra à jour bientôt :)

**Comment by ivangabriele** [comment]
@ClementChapalain Alors pour l'auto-complete, j'ai créé la tâche #65. Et pour les boutons j'ai  créé la #74.
