### ISSUE TITLE
amélioration de l'affichage des stats dashborad

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/code-du-travail-backoffice#506]
pour exporter les données dans excel pour faire des synthèses dans un tableau: Aujourd'hui, copier coller des données depuis le tableau de bord dans le site:

Proposition :

Afficher les pourcentages en colonne plutôt qu'en ligne 

ou

permettre l'export en csv des données

**Comment by ClementChapalain** [comment]
duplicates #508
