### ISSUE TITLE
Lier les références juridiques CC à l'API DILA

### ISSUE THREAD

**Issue by ClementChapalain** [SocialGouv/code-du-travail-backoffice#511]
Pour les 50 CCN : utiliser l'API DILA
Pour les autres : garder la possibilité d'ajouter un texte brut

**Comment by ivangabriele** [comment]
1. Créer un script pour "lier" automatiquement les références existantes (et migrer la base de données)
2. Revoir l'UI pour créer une complétion automatique pour les nouvelles références créées
3. Afficher le contenu des références liées dans la prévisualisation

Pour les étapes 2 et 3, il faut les intégrer tant côté administration que côté contribution.
