### ISSUE TITLE
[data] Exporter les données

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/code-du-travail-backoffice#972]
Comme nous avons des difficultés à récupérer les données via l'API, il faudrait trouver une solution pour exporter régulièrement les données.

Idées

### repo cdtn-contributions dédié

 - Créer un repo `cdtn-contributions` qui va historiser les données sous GIT
 - Pusher régulièrement (ex: toutes les 1h) sur ce repo **depuis la VM contribs**
 - dans le pipeline de ce repo, prévoir publication npm @socialgouv/cdtn-contributions

### repo cdtn-contributions dédié

 - Créer un repo `cdtn-contributions` qui va historiser les données sous GIT
 - dans le pipeline de ce repo,  créer un job manuel qui va récupérer (depuis un runner autorisé) les données contribs et les historiser dans GIT
 - dans le pipeline de ce repo, prévoir publication npm @socialgouv/cdtn-contributions

D'autres idées ?

**Comment by lionelB** [comment]
le flux a été fait https://github.com/SocialGouv/contributions-data
